EXAMPLE_POST_STUDY_REQUEST = {
    "study_number": "5678",
    "study_acronym": "STUDY-ACRONYM",
    "project_id": "AB1234",
    "description": "Study description",
}

EXAMPLE_POST_SOA_REQUEST = {
    "epochs": [
        {"reference_id": "epoch_001", "subtype": "C202487", "order": 1},
        {"reference_id": "epoch_002", "subtype": "C209541", "order": 2},
        {"reference_id": "epoch_003", "subtype": "C202578", "order": 3},
    ],
    "visits": [
        {
            "reference_id": "visit_002",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V2",
            "short_name": "V2",
            "number": 2,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": True,
            "window": {"before": 0, "after": 0, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 0,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_003",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V3",
            "short_name": "V3",
            "number": 3,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 3, "after": 3, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 30,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_004",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P4",
            "short_name": "P4",
            "number": 4,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 3, "after": 3, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 60,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_005",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V5",
            "short_name": "V5",
            "number": 5,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 3, "after": 3, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 91,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_006",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V6",
            "short_name": "V6",
            "number": 6,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 7, "after": 7, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 182,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_007",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V7",
            "short_name": "V7",
            "number": 7,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 7, "after": 7, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 273,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_008",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V8",
            "short_name": "V8",
            "number": 8,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 7, "after": 7, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 364,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_009",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P9",
            "short_name": "P9",
            "number": 9,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 455,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_010",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V10",
            "short_name": "V10",
            "number": 10,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 546,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_011",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P11",
            "short_name": "P11",
            "number": 11,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 637,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_012",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V12",
            "short_name": "V12",
            "number": 12,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 728,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_013",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P13",
            "short_name": "P13",
            "number": 13,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 819,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_014",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V14",
            "short_name": "V14",
            "number": 14,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 910,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_015",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P15",
            "short_name": "P15",
            "number": 15,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 1001,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_016",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V16",
            "short_name": "V16",
            "number": 16,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 1092,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_017",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "P17",
            "short_name": "P17",
            "number": 17,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 1183,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_018",
            "epoch_reference_id": "epoch_002",
            "type": "CTTerm_000181",
            "name": "V18",
            "short_name": "V18",
            "number": 18,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 10, "after": 10, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": 1274,
                "unit_uid": "UnitDefinition_000354",
            },
        },
        {
            "reference_id": "visit_301",
            "epoch_reference_id": "epoch_003",
            "type": "CTTerm_000172",
            "name": "EoS",
            "short_name": "EoS",
            "number": 20,
            "class": "UNSCHEDULED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000080",
        },
        {
            "reference_id": "visit_001",
            "epoch_reference_id": "epoch_001",
            "type": "CTTerm_000179",
            "name": "V1",
            "short_name": "V1",
            "number": 1,
            "class": "MANUALLY_DEFINED_VISIT",
            "subclass": "SINGLE_VISIT",
            "contact_mode": "CTTerm_000078",
            "is_global_anchor_visit": False,
            "window": {"before": 0, "after": 0, "unit_uid": "UnitDefinition_000354"},
            "timing": {
                "timing_reference_uid": "CTTerm_000123",
                "value": -35,
                "unit_uid": "UnitDefinition_000354",
            },
        },
    ],
    "activities": [
        {
            "reference_id": "activity_001",
            "visit_reference_ids": ["visit_001"],
            "activity_uid": "Activity_000122",
            "soa_group_uid": "CTTerm_000072",
            "activity_group_uid": "ActivityGroup_000006",
            "activity_subgroup_uid": "ActivitySubGroup_000180",
        },
        {
            "reference_id": "activity_002",
            "visit_reference_ids": ["visit_001"],
            "activity_uid": "Activity_000129",
            "soa_group_uid": "CTTerm_000065",
            "activity_group_uid": "ActivityGroup_000002",
            "activity_subgroup_uid": "ActivitySubGroup_000008",
        },
        {
            "reference_id": "activity_003",
            "visit_reference_ids": [
                "visit_001",
                "visit_002",
                "visit_003",
                "visit_004",
                "visit_301",
            ],
            "activity_uid": "Activity_000125",
            "soa_group_uid": "CTTerm_000065",
            "activity_group_uid": "ActivityGroup_000003",
            "activity_subgroup_uid": "ActivitySubGroup_000006",
        },
    ],
}
