server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        proxy_pass http://frontend:5005/;
    }

    location /api/ {
        proxy_pass http://api:5003/;
        proxy_read_timeout 300;
    }

    location /consumer-api/ {
        proxy_pass http://consumerapi:5008/;
        proxy_read_timeout 300;
    }

    location /extensions-api/ {
        proxy_pass http://extensionsapi:5009/;
        proxy_read_timeout 300;
    }

    location /doc/ {
        proxy_pass http://documentation:5006/;
    }

    location /neodash/ {
        proxy_pass http://neodash:5007/;
    }

    location /browser/ {
        proxy_pass http://database:7474/browser/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
