"""File containing all endpoints that are covered by load tests,
including endpoint urls and relevant paramters"""

# (<url>, <dictionary of query params>)
GET_ENDPOINTS = [
    ("/activity-instance-classes", None),
    ("/activity-instance-classes/headers", {"field_name": "name"}),
    ("/activity-instruction-pre-instances", None),
    ("/activity-instruction-pre-instances/audit-trail", None),
    ("/activity-instruction-pre-instances/headers", {"field_name": "name"}),
    ("/activity-instruction-templates", None),
    ("/activity-instruction-templates/audit-trail", None),
    ("/activity-instruction-templates/headers", {"field_name": "name"}),
    ("/activity-instructions", None),
    ("/activity-instructions/audit-trail", None),
    ("/activity-instructions/headers", {"field_name": "name"}),
    ("/activity-item-classes", None),
    ("/activity-item-classes/headers", {"field_name": "name"}),
    ("/admin/caches", None),
    ("/brands", None),
    ("/clinical-programmes", None),
    ("/clinical-programmes/headers", {"field_name": "name"}),
    ("/concepts/activities/activities", None),
    ("/concepts/activities/activities/headers", {"field_name": "name"}),
    ("/concepts/activities/activities/headers", {"field_name": "name", "lite": "true"}),
    ("/concepts/activities/activities/versions", None),
    ("/concepts/activities/activity-groups", None),
    ("/concepts/activities/activity-groups/headers", {"field_name": "name"}),
    ("/concepts/activities/activity-groups/versions", None),
    ("/concepts/activities/activity-instances", None),
    ("/concepts/activities/activity-instances/headers", {"field_name": "name"}),
    ("/concepts/activities/activity-instances/headers", {"field_name": "name", "lite": "true"}),
    ("/concepts/activities/activity-instances/versions", None),
    ("/concepts/activities/activity-sub-groups", None),
    ("/concepts/activities/activity-sub-groups/headers", {"field_name": "name"}),
    ("/concepts/activities/activity-sub-groups/versions", None),
    ("/concepts/compound-aliases", None),
    ("/concepts/compound-aliases/versions", None),
    ("/concepts/compound-aliases/headers", {"field_name": "name"}),
    ("/concepts/compounds", None),
    ("/concepts/compounds-simple", None),
    ("/concepts/compounds/versions", None),
    ("/concepts/compounds/headers", {"field_name": "name"}),
    ("/concepts/lag-times", None),
    ("/concepts/lag-times/headers", {"field_name": "name"}),
    ("/concepts/numeric-values", None),
    ("/concepts/numeric-values-with-unit", None),
    ("/concepts/numeric-values-with-unit/headers", {"field_name": "name"}),
    ("/concepts/numeric-values/headers", {"field_name": "name"}),
    ("/odms/metadata/aliases", None),
    ("/odms/metadata/descriptions", None),
    ("/odms/metadata/formal-expressions", None),
    ("/odms/conditions", None),
    ("/odms/conditions/headers", {"field_name": "name"}),
    ("/odms/forms", None),
    ("/odms/forms/headers", {"field_name": "name"}),
    ("/odms/forms/study-events", None),
    ("/odms/item-groups", None),
    ("/odms/item-groups/forms", None),
    ("/odms/item-groups/headers", {"field_name": "name"}),
    ("/odms/items", None),
    ("/odms/items/headers", {"field_name": "name"}),
    ("/odms/items/item-groups", None),
    ("/odms/metadata/xmls/stylesheets", None),
    ("/odms/methods", None),
    ("/odms/methods/headers", {"field_name": "name"}),
    ("/odms/study-events", None),
    ("/odms/study-events/headers", {"field_name": "name"}),
    ("/odms/vendor-attributes", None),
    ("/odms/vendor-attributes/headers", {"field_name": "name"}),
    ("/odms/vendor-elements", None),
    ("/odms/vendor-elements/headers", {"field_name": "name"}),
    ("/odms/vendor-namespaces", None),
    ("/odms/vendor-namespaces/headers", {"field_name": "name"}),
    ("/concepts/study-days", None),
    ("/concepts/study-days/headers", {"field_name": "name"}),
    ("/concepts/study-duration-days", None),
    ("/concepts/study-duration-days/headers", {"field_name": "name"}),
    ("/concepts/study-duration-weeks", None),
    ("/concepts/study-duration-weeks/headers", {"field_name": "name"}),
    ("/concepts/study-weeks", None),
    ("/concepts/study-weeks/headers", {"field_name": "name"}),
    ("/concepts/text-values", None),
    ("/concepts/text-values/headers", {"field_name": "name"}),
    ("/concepts/time-points", None),
    ("/concepts/time-points/headers", {"field_name": "name"}),
    ("/concepts/unit-definitions", None),
    ("/concepts/unit-definitions/headers", {"field_name": "name"}),
    ("/concepts/visit-names", None),
    ("/concepts/visit-names/headers", {"field_name": "name"}),
    ("/configurations", None),
    ("/criteria", None),
    ("/criteria-pre-instances", None),
    ("/criteria-pre-instances/audit-trail", None),
    ("/criteria-pre-instances/headers", {"field_name": "name"}),
    ("/criteria-templates", None),
    ("/criteria-templates/audit-trail", None),
    ("/criteria-templates/headers", {"field_name": "name"}),
    ("/criteria/audit-trail", None),
    ("/criteria/headers", {"field_name": "name"}),
    ("/ct/catalogues", None),
    ("/ct/codelists", {"page_size": "100", "total_count": "true"}),
    ("/ct/codelists/terms", {"codelist_uid": "{codelist_uid}"}),
    ("/ct/codelists/terms/headers", {"codelist_uid": "{codelist_uid}", "field_name": "term_uid"}),
    ("/ct/codelists/attributes", None),
    ("/ct/codelists/attributes/headers", {"field_name": "name"}),
    ("/ct/codelists/headers", {"field_name": "name.name"}),
    ("/ct/codelists/names", None),
    ("/ct/codelists/names/headers", {"field_name": "name"}),
    ("/ct/codelists/{codelist_uid}/terms", {"page_size": "100", "total_count": "true"}),
    ("/ct/codelists/{codelist_uid}/paired", None),
    ("/ct/codelists/{codelist_uid}/attributes", None),
    ("/ct/codelists/{codelist_uid}/attributes/versions", None),
    ("/ct/codelists/{codelist_uid}/names", None),
    ("/ct/codelists/{codelist_uid}/names/versions", None),
    ("/ct/codelists/{codelist_uid}/sub-codelists", {"term_uids": "CTTerm_000001"}),
    ("/ct/packages", None),
    (
        "/ct/packages/changes",
        {
            "catalogue_name": "SDTM CT",
            "old_package_date": "2014-09-26",
            "new_package_date": "2014-12-19",
        },
    ),
    ("/ct/packages/dates", {"catalogue_name": "SDTM CT"}),
    (
        "/ct/packages/{codelist_uid}/changes",
        {
            "catalogue_name": "SDTM CT",
            "old_package_date": "2014-09-26",
            "new_package_date": "2014-12-19",
        },
    ),
    ("/ct/stats", None),
    ("/ct/terms", {"page_size": "100", "total_count": "true"}),
    ("/ct/terms/attributes", None),
    ("/ct/terms/attributes/headers", {"field_name": "term_uid"}),
    ("/ct/terms/headers", {"field_name": "term_uid"}),
    ("/ct/terms/names", None),
    ("/ct/terms/names/headers", {"field_name": "term_uid"}),
    ("/ct/terms/{term_uid}/attributes", None),
    ("/ct/terms/{term_uid}/attributes/versions", None),
    ("/ct/terms/{term_uid}/names", None),
    ("/ct/terms/{term_uid}/names/versions", None),
    ("/dictionaries/codelists", {"library_name": "SNOMED"}),
    ("/dictionaries/codelists/headers", {"field_name": "name", "library_name": "SNOMED"}),
    ("/dictionaries/substances", {"page_size": "100", "total_count": "true"}),
    ("/dictionaries/terms", {"codelist_uid": "C100130"}),
    ("/dictionaries/terms/headers", {"field_name": "name", "codelist_uid": "C100130"}),
    ("/endpoint-pre-instances", None),
    ("/endpoint-pre-instances/audit-trail", None),
    ("/endpoint-pre-instances/headers", {"field_name": "name"}),
    ("/endpoint-templates", None),
    ("/endpoint-templates/audit-trail", None),
    ("/endpoint-templates/headers", {"field_name": "name"}),
    ("/endpoints", None),
    ("/endpoints/audit-trail", None),
    ("/endpoints/headers", {"field_name": "name"}),
    ("/epochs/allowed-configs", None),
    ("/footnote-pre-instances", None),
    ("/footnote-pre-instances/audit-trail", None),
    ("/footnote-pre-instances/headers", {"field_name": "name"}),
    ("/footnote-templates", None),
    ("/footnote-templates/audit-trail", None),
    ("/footnote-templates/headers", {"field_name": "name"}),
    ("/footnotes", None),
    ("/footnotes/audit-trail", None),
    ("/footnotes/headers", {"field_name": "name"}),
    ("/libraries", None),
    ("/listings/libraries/all/gcmd/cdisc-ct-list", None),
    ("/listings/libraries/all/gcmd/cdisc-ct-list/headers", {"field_name": "name"}),
    ("/listings/libraries/all/gcmd/cdisc-ct-pkg", None),
    ("/listings/libraries/all/gcmd/cdisc-ct-pkg/headers", {"field_name": "name"}),
    ("/listings/libraries/all/gcmd/cdisc-ct-ver", None),
    ("/listings/libraries/all/gcmd/cdisc-ct-ver/headers", {"field_name": "name"}),
    ("/listings/libraries/all/gcmd/topic-cd-def", None),
    ("/listings/libraries/all/gcmd/topic-cd-def/headers", {"field_name": "name"}),
    ("/listings/metadata", None),
    ("/listings/metadata/headers", {"field_name": "name"}),
    # This endpoint requires a released study
    # (
    #     "/listings/studies/study-metadata",
    #     {"study_number": "{study_number}", "project_id": "{project_id}", "datetime": "<now>"},
    # ),
    ("/listings/studies/{study_uid}/adam/mdendpnt", None),
    ("/listings/studies/{study_uid}/adam/mdendpnt/headers", {"field_name": "OBJTVLVL"}),
    ("/listings/studies/{study_uid}/adam/mdvisit", None),
    ("/listings/studies/{study_uid}/adam/mdvisit/headers", {"field_name": "VISTPCD"}),
    ("/listings/studies/{study_uid}/sdtm/ta", None),
    ("/listings/studies/{study_uid}/sdtm/tdm", None),
    ("/listings/studies/{study_uid}/sdtm/te", None),
    ("/listings/studies/{study_uid}/sdtm/ti", None),
    ("/listings/studies/{study_uid}/sdtm/ts", None),
    ("/listings/studies/{study_uid}/sdtm/tv", None),
    ("/objective-pre-instances", None),
    ("/objective-pre-instances/audit-trail", None),
    ("/objective-pre-instances/headers", {"field_name": "name"}),
    ("/objective-templates", None),
    ("/objective-templates/audit-trail", None),
    ("/objective-templates/headers", {"field_name": "name"}),
    ("/objectives", None),
    ("/objectives/audit-trail", None),
    ("/objectives/headers", {"field_name": "name"}),
    ("/projects", None),
    ("/projects/headers", {"field_name": "name"}),
    (
        "/standards/class-variables",
        {"data_model_name": "SDTM", "data_model_version": "2.0", "dataset_class_name": "Demographics"},
    ),
    (
        "/standards/class-variables/headers",
        {
            "data_model_name": "SDTM",
            "data_model_version": "2.0",
            "dataset_class_name": "Demographics",
            "field_name": "label",
        },
    ),
    ("/standards/data-model-igs", None),
    ("/standards/data-model-igs/headers", {"field_name": "name"}),
    ("/standards/data-models", None),
    ("/standards/data-models/headers", {"field_name": "name"}),
    ("/standards/dataset-classes", None),
    ("/standards/dataset-classes/headers", {"field_name": "uid"}),
    (
        "/standards/dataset-scenarios",
        {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "2.0"},
    ),
    (
        "/standards/dataset-scenarios/headers",
        {
            "data_model_ig_name": "SDTMIG",
            "data_model_ig_version": "2.0",
            "field_name": "label",
        },
    ),
    ("/standards/dataset-variables", {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2"}),
    (
        "/standards/dataset-variables/headers",
        {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2", "field_name": "label"},
    ),
    ("/standards/datasets", {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2"}),
    (
        "/standards/datasets/headers",
        {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2", "field_name": "label"},
    ),
    # ("/standards/sponsor-models/dataset-classes", None),
    # ("/standards/sponsor-models/dataset-classes/headers", {"field_name": "uid"}),
    ("/standards/sponsor-models/dataset-variables", {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2"}),
    (
        "/standards/sponsor-models/dataset-variables/headers",
        {"data_model_ig_name": "SDTMIG", "data_model_ig_version": "3.2", "field_name": "label"},
    ),
    ("/standards/sponsor-models/datasets", None),
    ("/standards/sponsor-models/datasets/headers", {"field_name": "xml_title"}),
    ("/standards/sponsor-models/models", None),
    ("/standards/sponsor-models/models/headers", {"field_name": "name"}),
    # ("/standards/sponsor-models/variable-classes", None),
    # ("/standards/sponsor-models/variable-classes/headers", {"field_name": "label"}),
    ("/studies", None),
    ("/studies/list", None),
    ("/studies/list", {"minimal_response=false": "false"}),
    ("/studies/headers", {"field_name": "name"}),
    ("/studies/structure-overview", None),
    ("/studies/structure-overview/headers", {"field_name": "study_ids"}),
    ("/studies/{study_uid}/audit-trail", None),
    ("/studies/{study_uid}/detailed-soa-exports", None),
    ("/studies/{study_uid}/detailed-soa-history", None),
    ("/studies/{study_uid}/flowchart", {"layout": "detailed"}),
    ("/studies/{study_uid}/flowchart", {"layout": "protocol"}),
    ("/studies/{study_uid}/flowchart", {"layout": "operational"}),
    ("/studies/{study_uid}/flowchart.docx", {"layout": "detailed"}),
    ("/studies/{study_uid}/flowchart.docx", {"layout": "protocol"}),
    ("/studies/{study_uid}/flowchart.docx", {"layout": "operational"}),
    ("/studies/{study_uid}/flowchart.html", {"layout": "detailed"}),
    ("/studies/{study_uid}/flowchart.html", {"layout": "protocol"}),
    ("/studies/{study_uid}/flowchart.html", {"layout": "operational"}),
    ("/studies/{study_uid}/flowchart/coordinates", None),
    ("/studies/{study_uid}/protocol-soa-exports", None),
    ("/studies/{study_uid}/operational-soa.html", None),
    ("/studies/{study_uid}/operational-soa.xlsx", None),
    ("/studies/{study_uid}/pharma-cm", None),
    ("/studies/{study_uid}/pharma-cm.xml", None),
    ("/studies/{study_uid}/soa-preferences", None),
    ("/studies/{study_uid}", None),
    ("/studies/{study_uid}/allowed-consecutive-groups", None),
    ("/studies/{study_uid}/anchor-visits-for-special-visit", {"study_epoch_uid": "StudyEpoch_000021"}),
    ("/studies/{study_uid}/anchor-visits-in-group-of-subvisits", None),
    ("/studies/{study_uid}/ctr/odm.xml", None),
    ("/studies/{study_uid}/design.svg", None),
    ("/studies/{study_uid}/fields-audit-trail", None),
    # ("/studies/{study_uid}/global-anchor-visit", None),
    ("/studies/{study_uid}/interventions", None),
    ("/studies/{study_uid}/interventions.docx", None),
    ("/studies/{study_uid}/interventions.html", None),
    ("/studies/{study_uid}/protocol-title", None),
    ("/studies/{study_uid}/snapshot-history", None),
    ("/studies/{study_uid}/study-activity-groups", None),
    ("/studies/{study_uid}/study-activity-instances/audit-trail", None),
    ("/studies/{study_uid}/study-activity-subgroups", None),
    ("/studies/{study_uid}/study-activities", None),
    ("/studies/{study_uid}/study-activities/audit-trail", None),
    ("/studies/{study_uid}/study-activities/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-activity-instructions", None),
    ("/studies/{study_uid}/study-activity-schedules", None),
    ("/studies/{study_uid}/study-activity-schedules/audit-trail/", None),
    ("/studies/{study_uid}/study-arms", None),
    ("/studies/{study_uid}/study-arms/audit-trail", None),
    ("/studies/{study_uid}/study-arms/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-branch-arm/audit-trail", None),
    ("/studies/{study_uid}/study-branch-arms", None),
    ("/studies/{study_uid}/study-cohort/audit-trail", None),
    ("/studies/{study_uid}/study-cohorts", None),
    ("/studies/{study_uid}/study-compound-dosings", None),
    ("/studies/{study_uid}/study-compound-dosings/audit-trail", None),
    ("/studies/{study_uid}/study-compound-dosings/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-compounds", None),
    ("/studies/{study_uid}/study-compounds/audit-trail", None),
    ("/studies/{study_uid}/study-compounds/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-criteria", None),
    ("/studies/{study_uid}/study-criteria/audit-trail", None),
    ("/studies/{study_uid}/study-criteria/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-design-cells", None),
    ("/studies/{study_uid}/study-design-cells/arm/{arm_uid}", None),
    ("/studies/{study_uid}/study-design-cells/audit-trail/", None),
    ("/studies/{study_uid}/study-disease-milestones", None),
    ("/studies/{study_uid}/study-disease-milestones/audit-trail", None),
    ("/studies/{study_uid}/study-disease-milestones/headers", {"field_name": "uid"}),
    ("/studies/{study_uid}/study-element/audit-trail", None),
    ("/studies/{study_uid}/study-elements", None),
    ("/studies/{study_uid}/study-elements/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-endpoints", None),
    ("/studies/{study_uid}/study-endpoints/audit-trail", None),
    ("/studies/{study_uid}/study-endpoints/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-epochs/audit-trail", None),
    ("/studies/{study_uid}/study-epochs", None),
    ("/studies/{study_uid}/study-epochs/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-objectives", None),
    ("/studies/{study_uid}/study-objectives.docx", None),
    ("/studies/{study_uid}/study-objectives.html", None),
    ("/studies/{study_uid}/study-objectives/audit-trail", None),
    ("/studies/{study_uid}/study-objectives/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-soa-groups", None),
    ("/studies/{study_uid}/study-soa-footnote/audit-trail", None),
    ("/studies/{study_uid}/study-soa-footnotes", None),
    ("/studies/{study_uid}/study-soa-footnotes/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/study-standard-versions", None),
    ("/studies/{study_uid}/study-standard-versions/audit-trail", None),
    ("/studies/{study_uid}/study-visits/audit-trail", None),
    ("/studies/{study_uid}/study-visits", None),
    ("/studies/{study_uid}/study-visits-references", None),
    ("/studies/{study_uid}/study-visits/allowed-time-references", None),
    ("/studies/{study_uid}/study-visits/headers", {"field_name": "name"}),
    ("/studies/{study_uid}/time-units", None),
    ("/study-activities", None),
    ("/study-activity-instructions", None),
    ("/study-arms", None),
    ("/study-compound-dosings/headers", {"field_name": "name"}),
    ("/study-compounds", None),
    ("/study-compounds/headers", {"field_name": "name"}),
    ("/study-criteria", None),
    ("/study-criteria/headers", {"field_name": "name"}),
    ("/study-elements/allowed-element-configs", None),
    ("/study-endpoints", None),
    ("/study-endpoints/headers", {"field_name": "name"}),
    ("/study-objectives", None),
    ("/study-objectives/headers", {"field_name": "name"}),
    ("/study-soa-footnotes", None),
    ("/study-soa-footnotes/headers", {"field_name": "name"}),
    ("/template-parameters", None),
    ("/template-parameters/{name}/terms", None),
    ("/timeframe-templates", None),
    ("/timeframe-templates/audit-trail", None),
    ("/timeframe-templates/headers", {"field_name": "name"}),
    ("/timeframes", None),
    ("/timeframes/audit-trail", None),
    ("/timeframes/headers", {"field_name": "name"}),
    ("/comment-threads", None),
    ("/comment-topics", None),
    ("/concepts/active-substances", None),
    ("/concepts/active-substances/versions", None),
    ("/concepts/active-substances/headers", {"field_name": "uid"}),
    ("/concepts/medicinal-products", None),
    ("/concepts/medicinal-products/versions", None),
    ("/concepts/medicinal-products/headers", {"field_name": "uid"}),
    ("/concepts/pharmaceutical-products", None),
    ("/concepts/pharmaceutical-products/versions", None),
    ("/concepts/pharmaceutical-products/headers", {"field_name": "uid"}),
    ("/studies/{study_uid}/operational-soa-exports", None),
    ("/studies/{study_uid}/study-activity-instances", None),
    ("/studies/{study_uid}/study-activity-instances/headers", {"field_name": "activity"}),
    ("/studies/{study_uid}/complexity-score", None),
    ("/study-activity-instances", None),
    ("/usdm/v3/studyDefinitions/{study_uid}", None),
    ("/usdm/v3/studyDefinitions/{study_uid}/m11", None),
]

# These endpoints are terribly slow (>30 seconds) and are temporarily excluded from the load tests
EXTREMELY_SLOW_ENDPOINTS = [
    (
        "/ct/catalogues/changes",
        {"comparison_type": "sponsor", "start_datetime": "<now>"},
    ),
    ("/listings/libraries/all/gcmd/cdisc-ct-val", None),
    ("/listings/libraries/all/gcmd/cdisc-ct-val/headers", {"field_name": "name"}),
]


GET_ENDPOINTS_CONSUMER_API = [
    ("/v1/studies", None),
    ("/v1/studies/{study_uid}/study-visits", None),
    ("/v1/studies/{study_uid}/study-activities", None),
    ("/v1/studies/{study_uid}/study-activity-instances", None),
    ("/v1/studies/{study_uid}/detailed-soa", None),
    ("/v1/studies/{study_uid}/operational-soa", None),
    ("/v1/studies/audit-trail", {"from_ts": "2024-01-01T00:00:00Z", "to_ts": "<now>"}),
    ("/v1/library/activities", None),
    ("/v1/library/activities", {"library": "Sponsor", "status": "Final"}),
    ("/v1/library/activity-instances", None),
    ("/v1/library/activity-instances", {"library": "Sponsor", "status": "Final"}),
    ("/v1/library/ct/codelists", None),
    ("/v1/library/ct/codelist-terms", {"codelist_submission_value": "EPOCHSTP"}),
    ("/v1/library/unit-definitions", None),
]
