import csv
import os

from junit_xml import TestCase, TestSuite

from tests.utils import Params, get_logger

logger = get_logger(os.path.basename(__file__))


def _get_error(url: str, failures: list[dict]):
    for failure in failures:
        if url == failure["url"]:
            return failure["error"]
    return ""


def generate_summary():
    """Generates JUnit xml test report listing all tested endpoints and their reponse times.
    Endpoints with reponse times higher than PERFORMANCE_THRESHOLD are marked as test failures.

    Input to this summary is `test_report_stats.csv` file generated by locust (by running `pipenv run load-test-cl`)
    """

    summary_stats = []
    slow_endpoints = []
    failures = []

    with open("test_report_failures.csv", encoding="utf-8", errors="ignore") as csv_file:
        for line in csv.DictReader(csv_file):
            failures.append(
                {
                    "url": line["Name"],
                    "error": line["Error"],
                }
            )

    filename = "test_report_stats.csv"
    with open(filename, encoding="utf-8", errors="ignore") as csv_file:
        for line in csv.DictReader(csv_file):
            summary_stats.append(
                {
                    "url": line["Name"],
                    "median_response_time": line["Median Response Time"],
                    "failure_count": line["Failure Count"],
                    "request_count": line["Request Count"],
                }
            )

    summary_stats = sorted(summary_stats, key=lambda x: float(x["median_response_time"]), reverse=True)

    # Generate JUnit xml report
    test_cases = []
    for x in summary_stats:
        failures_msg = f", Failures: {x['failure_count']}/{x['request_count']}" if int(x["failure_count"]) > 0 else ""
        test_case_name = f'{x["url"]} [Median: {int(float(x["median_response_time"]))}ms{failures_msg}]'
        test_case: TestCase = TestCase(test_case_name, "some.class.name", 1)

        if float(x["median_response_time"]) > Params.PERFORMANCE_THRESHOLD or int(x["failure_count"]) > 0:
            logger.warning("%s: %sms %s", x["url"], x["median_response_time"], _get_error(x["url"], failures))
            slow_endpoints.append(test_case_name)

            if float(x["median_response_time"]) > Params.PERFORMANCE_THRESHOLD:
                test_case.add_failure_info(message=f"Response time is bigger than {Params.PERFORMANCE_THRESHOLD}ms")

            if int(x["failure_count"]) > 0:
                test_case.add_failure_info(message=_get_error(x["url"], failures))

        test_cases.append(test_case)

    test_suite = TestSuite("Load Tests", test_cases)
    with open("summary_report.xml", "w", encoding="utf-8") as junit_report:
        TestSuite.to_file(junit_report, [test_suite])

    print(f"Summary report generated at {os.path.abspath('summary_report.xml')}")
    assert len(slow_endpoints) == 0


def round_up_numbers():
    """Rounds up numbers in `test_report_stats.csv` file to nearest integer, so that Excel can read it properly."""

    file = "test_report_stats.csv"
    file_rounded = "test_report_stats_rounded.csv"

    with open(file, encoding="utf-8", errors="ignore") as csv_file:
        with open(file_rounded, "w", encoding="utf-8") as csv_file_rounded:
            csv_reader = csv.DictReader(csv_file)
            csv_writer = csv.DictWriter(csv_file_rounded, fieldnames=csv_reader.fieldnames)
            csv_writer.writeheader()

            for line in csv_reader:
                line["Median Response Time"] = str(round(float(line["Median Response Time"])))
                line["Average Response Time"] = str(round(float(line["Average Response Time"])))
                line["Min Response Time"] = str(round(float(line["Min Response Time"])))
                line["Max Response Time"] = str(round(float(line["Max Response Time"])))
                line["Average Content Size"] = str(round(float(line["Average Content Size"])))

                csv_writer.writerow(line)

    # Replace original file with the containing rounded numbers
    os.remove(file)
    os.rename(file_rounded, file)


if __name__ == "__main__":
    round_up_numbers()
    generate_summary()
